services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB:   ${DB_DATABASE:-testdb}
      POSTGRES_USER: ${DB_USERNAME:-testuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-testpass}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"

  php-fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
    environment:
      # вот здесь подаём все нужные скрипту переменные
      DB_HOST:      ${DB_HOST:-db}
      DB_DATABASE:  ${DB_DATABASE:-testdb}
      DB_USERNAME:  ${DB_USERNAME:-testuser}
      DB_PASSWORD:  ${DB_PASSWORD:-testpass}
      REDIS_HOST:   ${REDIS_HOST:-redis}
      REDIS_PORT:   ${REDIS_PORT:-6379}
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:ro
    depends_on:
      - php-fpm

   # 1) Экспортер метрик Nginx
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    ports:
      - "9113:9113"
    command:
      - "-nginx.scrape-uri=http://nginx:80/nginx_status"
    depends_on:
      - nginx

  # 2) Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - nginx-exporter

  # 3) Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus


volumes:
  db_data:
  grafana_data: